name: Open Pull Request

on:
  push:
    branches: ['feature/**']

permissions:
  contents: read
  pull-requests: write

jobs:
  open-pull-request:
    uses: ./.github/workflows/open-pull-request.yml
    with:
      base: develop
